# 🔍 CONFIGURAÇÃO SIMPLES DO PROMETHEUS - RSV 360° ECOSYSTEM

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus próprio
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Database
  - job_name: 'postgresql'
    static_configs:
      - targets: ['db-local:5432']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-local:6379']
