# 🏭 DOCKER COMPOSE - AMBIENTE DE PRODUÇÃO LOCAL
# RSV 360° ECOSYSTEM - Teste de Produção Local

version: '3.8'

services:
  # 🌐 ECOSYSTEM MASTER - Servidor Principal
  ecosystem-master-local:
    build:
      context: ../ECOSYSTEM-MASTER
      dockerfile: Dockerfile
    container_name: rsv-ecosystem-master-local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://rsvuser:rsvpassword@db-local:5432/rsv_ecosystem_local
      REDIS_URL: redis://redis-local:6379
      JWT_SECRET: rsv-local-jwt-secret-key-2025
      API_BASE_URL: http://localhost:3000
    depends_on:
      db-local:
        condition: service_healthy
      redis-local:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - rsv-local-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🗄️ POSTGRESQL DATABASE - Banco de Dados Local
  db-local:
    image: postgres:15-alpine
    container_name: rsv-db-local
    environment:
      POSTGRES_DB: rsv_ecosystem_local
      POSTGRES_USER: rsvuser
      POSTGRES_PASSWORD: rsvpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=pt_BR.UTF-8 --lc-ctype=pt_BR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - db_local_data:/var/lib/postgresql/data
      - ../INFRASTRUCTURE/database-cluster/schemas:/docker-entrypoint-initdb.d
      - ./config/local-database.yml:/etc/postgresql/local-database.yml
    networks:
      - rsv-local-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsvuser -d rsv_ecosystem_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🔴 REDIS CACHE - Cache e Sessões
  redis-local:
    image: redis:7-alpine
    container_name: rsv-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_local_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - rsv-local-network
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 📈 MONITORING - Monitoramento Local
  monitoring-local:
    image: prom/prometheus:latest
    container_name: rsv-monitoring-local
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_local_data:/prometheus
    networks:
      - rsv-local-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # 📊 GRAFANA DASHBOARD - Dashboard de Monitoramento
  grafana-local:
    image: grafana/grafana:latest
    container_name: rsv-grafana-local
    ports:
      - "3005:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: rsvadmin2025
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_local_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    networks:
      - rsv-local-network
    restart: unless-stopped
    depends_on:
      - monitoring-local

# 🌐 REDE LOCAL
networks:
  rsv-local-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 💾 VOLUMES PERSISTENTES
volumes:
  db_local_data:
    driver: local
  redis_local_data:
    driver: local
  prometheus_local_data:
    driver: local
  grafana_local_data:
    driver: local