version: '3.8'

services:
  # 🗄️ POSTGRESQL DATABASE - Banco de Dados Local
  db-local:
    image: postgres:15-alpine
    container_name: rsv-db-local
    environment:
      POSTGRES_DB: rsv_ecosystem_local
      POSTGRES_USER: rsvuser
      POSTGRES_PASSWORD: rsvpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=pt_BR.UTF-8 --lc-ctype=pt_BR.UTF-8"
    ports:
      - "5434:5432"
    volumes:
      - db_local_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsvuser -d rsv_ecosystem_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🔴 REDIS CACHE - Cache e Sessões
  redis-local:
    image: redis:7-alpine
    container_name: rsv-redis-local
    ports:
      - "6380:6379"
    volumes:
      - redis_local_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 📊 GRAFANA DASHBOARD - Dashboard de Monitoramento
  grafana-local:
    image: grafana/grafana:9.0.0
    container_name: rsv-grafana-local
    ports:
      - "3006:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: rsvadmin2025
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_local_data:/var/lib/grafana
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

# 💾 VOLUMES PERSISTENTES
volumes:
  db_local_data:
    driver: local
  redis_local_data:
    driver: local
  grafana_local_data:
    driver: local
