name: E2E Cross-Browser

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run E2E (Chromium, Firefox, WebKit)
        working-directory: frontend
        env:
          ALL_BROWSERS: '1'
        run: npm run test:e2e

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore

