# 🏭 DOCKER COMPOSE - SERVIÇOS ESSENCIAIS
# RSV 360° ECOSYSTEM - Apenas Banco e Redis

version: '3.8'

services:
  # 🗄️ POSTGRESQL DATABASE - Banco de Dados Local
  db-local:
    image: postgres:15-alpine
    container_name: rsv-db-local
    environment:
      POSTGRES_DB: rsv_ecosystem_local
      POSTGRES_USER: rsvuser
      POSTGRES_PASSWORD: rsvpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=pt_BR.UTF-8 --lc-ctype=pt_BR.UTF-8"
    ports:
      - "5434:5432"
    volumes:
      - db_local_data:/var/lib/postgresql/data
    networks:
      - rsv-local-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsvuser -d rsv_ecosystem_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🔴 REDIS CACHE - Cache e Sessões
  redis-local:
    image: redis:7-alpine
    container_name: rsv-redis-local
    ports:
      - "6380:6379"
    volumes:
      - redis_local_data:/data
    networks:
      - rsv-local-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

# 🌐 REDE LOCAL
networks:
  rsv-local-network:
    driver: bridge

# 💾 VOLUMES PERSISTENTES
volumes:
  db_local_data:
    driver: local
  redis_local_data:
    driver: local
