# 🚀 RSV 360° ECOSYSTEM - APLICAÇÕES
# Configuração das aplicações do ecossistema

version: '3.8'

services:
  # 🎯 ECOSYSTEM MASTER - Servidor Principal
  ecosystem-master-local:
    build:
      context: ../ECOSYSTEM-MASTER
      dockerfile: Dockerfile
    container_name: rsv-ecosystem-master-local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://rsvuser:rsvpassword@db-local:5432/rsv_ecosystem_local
      REDIS_URL: redis://redis-local:6379
      JWT_SECRET: rsv_jwt_secret_2025_local
    depends_on:
      - db-local
      - redis-local
    networks:
      - rsv-local-network
    restart: unless-stopped

  # 👥 CRM SYSTEM - Sistema de Gestão de Clientes
  crm-system-local:
    build:
      context: ../BUSINESS-MODULES/crm-system
      dockerfile: Dockerfile
    container_name: rsv-crm-system-local
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://rsvuser:rsvpassword@db-local:5432/rsv_ecosystem_local
      REDIS_URL: redis://redis-local:6379
      JWT_SECRET: rsv_jwt_secret_2025_local
    depends_on:
      - db-local
      - redis-local
    networks:
      - rsv-local-network
    restart: unless-stopped

  # 📅 BOOKING ENGINE - Motor de Reservas
  booking-engine-local:
    build:
      context: ../BUSINESS-MODULES/booking-engine
      dockerfile: Dockerfile
    container_name: rsv-booking-engine-local
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
      DATABASE_URL: postgresql://rsvuser:rsvpassword@db-local:5432/rsv_ecosystem_local
      REDIS_URL: redis://redis-local:6379
      JWT_SECRET: rsv_jwt_secret_2025_local
    depends_on:
      - db-local
      - redis-local
    networks:
      - rsv-local-network
    restart: unless-stopped

  # 🏨 HOTEL MANAGEMENT - Gestão de Hotéis
  hotel-management-local:
    build:
      context: ../BUSINESS-MODULES/hotel-management
      dockerfile: Dockerfile
    container_name: rsv-hotel-management-local
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      PORT: 3003
      DATABASE_URL: postgresql://rsvuser:rsvpassword@db-local:5432/rsv_ecosystem_local
      REDIS_URL: redis://redis-local:6379
      JWT_SECRET: rsv_jwt_secret_2025_local
    depends_on:
      - db-local
      - redis-local
    networks:
      - rsv-local-network
    restart: unless-stopped

  # 📊 ANALYTICS INTELLIGENCE - Inteligência de Dados
  analytics-intelligence-local:
    build:
      context: ../ANALYTICS-INTELLIGENCE
      dockerfile: Dockerfile
    container_name: rsv-analytics-intelligence-local
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: production
      PORT: 3004
      DATABASE_URL: postgresql://rsvuser:rsvpassword@db-local:5432/rsv_ecosystem_local
      REDIS_URL: redis://redis-local:6379
      JWT_SECRET: rsv_jwt_secret_2025_local
    depends_on:
      - db-local
      - redis-local
    networks:
      - rsv-local-network
    restart: unless-stopped

networks:
  rsv-local-network:
    external: true
